import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Yeshwantrao Chavan College of Engineering",
  description: "Generated by create next app",
  image: "https://example.com/image.jpg",
  icons: {
    icon: '/ycce_logo.png', // /public path
    apple: '/ycce_logo.png', // /public path
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
